var CARE_DATA = {
  hospitals: [
    {
      id: 1,
      name: "St. Jude General Hospital & Trauma Center",
      city: "Mumbai",
      state: "Maharashtra",
      address: "450 Medical Center Plaza, Bandra West, Mumbai, MH 400050",
      phone: "+91 (22) 5550-0199",
      emergency_hotline: "+91 102 / +91 (22) 5550-9111",
      rating: 4.9,
      reviews_count: 342,
      er_open: true,
      available_er_beds: 12,
      available_icu_beds: 5,
      trauma_level: "Level 1 Trauma Center",
      departments: ["Cardiologist", "Neurologist", "Orthopedic Doctor", "Dentist", "Psychiatrist"],
      image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: 5,
      name: "Bhopal AIIMS & Apex Trauma Center",
      city: "Bhopal",
      state: "Madhya Pradesh",
      address: "Saket Nagar, AIIMS Campus, Bhopal, MP 462020",
      phone: "+91 (755) 297-0010",
      emergency_hotline: "+91 (755) 297-9111",
      rating: 4.9,
      reviews_count: 420,
      er_open: true,
      available_er_beds: 18,
      available_icu_beds: 9,
      trauma_level: "Level 1 Trauma Center",
      departments: ["General Physician", "Neurologist", "Pediatrician", "Dentist", "General Surgeon"],
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: 11,
      name: "Metro Health Institute Delhi",
      city: "Delhi",
      state: "Delhi NCR",
      address: "Ring Road, Lajpat Nagar, New Delhi, DL 110024",
      phone: "+91 (11) 4560-0144",
      emergency_hotline: "+91 (11) 4560-9900",
      rating: 4.8,
      reviews_count: 289,
      er_open: true,
      available_er_beds: 8,
      available_icu_beds: 3,
      trauma_level: "Level 2 Regional Emergency",
      departments: ["Dermatologist", "Gynecologist", "ENT Specialist", "Pulmonologist"],
      image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: 15,
      name: "Bengaluru Multi-Specialty Heart Institute",
      city: "Bengaluru",
      state: "Karnataka",
      address: "100 Feet Road, Indiranagar, Bengaluru, KA 560038",
      phone: "+91 (80) 2500-1122",
      emergency_hotline: "+91 (80) 2500-9111",
      rating: 4.9,
      reviews_count: 512,
      er_open: true,
      available_er_beds: 20,
      available_icu_beds: 10,
      trauma_level: "Level 1 Trauma Center",
      departments: ["Cardiologist", "Orthopedic Doctor", "Pediatrician", "Gastroenterologist", "Psychiatrist"],
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: 22,
      name: "Chennai Apollo Main Hospital",
      city: "Chennai",
      state: "Tamil Nadu",
      address: "21, Greams Lane, Off Greams Road, Thousand Lights, Chennai, TN 600006",
      phone: "+91 (44) 2829-0200",
      emergency_hotline: "+91 (44) 2829-9111",
      rating: 5.0,
      reviews_count: 680,
      er_open: true,
      available_er_beds: 22,
      available_icu_beds: 12,
      trauma_level: "Level 1 Trauma Center",
      departments: ["Cardiologist", "Endocrinologist", "ENT Specialist"],
      image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=600&auto=format&fit=crop&q=80"
    },
    {
      id: 24,
      name: "Kolkata AMRI Hospitals",
      city: "Kolkata",
      state: "West Bengal",
      address: "P-4&5, CIT Scheme LXXII, Block A, Gariahat, Kolkata, WB 700029",
      phone: "+91 (33) 6680-0000",
      emergency_hotline: "+91 (33) 6680-9111",
      rating: 4.8,
      reviews_count: 340,
      er_open: true,
      available_er_beds: 12,
      available_icu_beds: 5,
      trauma_level: "Level 2 Regional Emergency",
      departments: ["Ophthalmologist", "Psychiatrist", "Pediatrician"],
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80"
    }
  ],

  doctors: [
    // --- 1. ANDHRA PRADESH ---
    {
      id: 1,
      name: "Dr. Gurleen Kaur, MD",
      title: "Senior Cardiologist",
      specialty: "Cardiologist",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      hospital_name: "Apollo Hospital Visakhapatnam",
      rating: 4.9,
      reviews_count: 240,
      fee: 1200,
      experience: 15,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80",
      bio: "Cardiovascular health, BP management, angiography evaluation, and preventive heart care.",
      accepted_insurances: ["Star Health", "Ayushman Bharat"],
      slots: ["10:00 AM", "02:00 PM", "05:00 PM"]
    },
    {
      id: 2,
      name: "Dr. Rajesh Malhotra, MD",
      title: "Senior Cardiologist",
      specialty: "Cardiologist",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      hospital_name: "Visakha Heart Institute",
      rating: 4.9,
      reviews_count: 310,
      fee: 1500,
      experience: 18,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80",
      bio: "Interventional cardiology, heart failure management, and coronary angioplasty specialist.",
      accepted_insurances: ["Star Health", "HDFC ERGO"],
      slots: ["09:00 AM", "01:00 PM", "04:30 PM"]
    },
    {
      id: 3,
      name: "Dr. Simran Kaur, MD",
      title: "Consultant Gynecologist",
      specialty: "Gynecologist",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      hospital_name: "Care Women Center Visakhapatnam",
      rating: 4.8,
      reviews_count: 195,
      fee: 1000,
      experience: 12,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80",
      bio: "High-risk pregnancy care, maternity wellness, laparoscopic surgery, and PCOS management.",
      accepted_insurances: ["Care Health", "Star Health"],
      slots: ["11:00 AM", "02:30 PM", "05:30 PM"]
    },

    // --- 2. ARUNACHAL PRADESH ---
    {
      id: 4,
      name: "Dr. Shivani Sharma, MD",
      title: "Senior Dermatologist",
      specialty: "Dermatologist",
      city: "Itanagar",
      state: "Arunachal Pradesh",
      hospital_name: "Itanagar Specialty Clinic",
      rating: 4.9,
      reviews_count: 180,
      fee: 900,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80",
      bio: "Skin allergy care, acne treatments, hair fall therapies, and cosmetic dermatology.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:00 PM"]
    },
    {
      id: 5,
      name: "Dr. Sarah Bennett, MD",
      title: "Interventional Cardiologist",
      specialty: "Cardiologist",
      city: "Itanagar",
      state: "Arunachal Pradesh",
      hospital_name: "Itanagar Heart & General Hospital",
      rating: 4.9,
      reviews_count: 210,
      fee: 1400,
      experience: 14,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&auto=format&fit=crop&q=80",
      bio: "Cardiac catheterization, hypertension management, and preventive cardiovascular care.",
      accepted_insurances: ["Star Health", "Max Bupa"],
      slots: ["09:30 AM", "01:00 PM", "04:30 PM"]
    },
    {
      id: 6,
      name: "Dr. Siddarth Verma, MS",
      title: "Senior Neurologist",
      specialty: "Neurologist",
      city: "Itanagar",
      state: "Arunachal Pradesh",
      hospital_name: "Arunachal Neuro Center",
      rating: 4.8,
      reviews_count: 160,
      fee: 1100,
      experience: 13,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80",
      bio: "Stroke rehabilitation, nerve pain therapies, migraine relief, and brain health.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["10:30 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 3. ASSAM ---
    {
      id: 7,
      name: "Dr. Sakshi Gupta, MD",
      title: "Lead Pediatrician",
      specialty: "Pediatrician",
      city: "Guwahati",
      state: "Assam",
      hospital_name: "Guwahati Children Hospital",
      rating: 4.9,
      reviews_count: 230,
      fee: 800,
      experience: 12,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&auto=format&fit=crop&q=80",
      bio: "Child immunization schedules, growth tracking, newborn nutrition, and pediatric care.",
      accepted_insurances: ["Star Health", "Ayushman Bharat"],
      slots: ["09:00 AM", "12:30 PM", "03:30 PM"]
    },
    {
      id: 8,
      name: "Dr. Anil Kapoor, MS",
      title: "Senior Orthopedic Surgeon",
      specialty: "Orthopedic Doctor",
      city: "Guwahati",
      state: "Assam",
      hospital_name: "Guwahati Ortho & Trauma Center",
      rating: 4.9,
      reviews_count: 290,
      fee: 1200,
      experience: 17,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80",
      bio: "Knee replacement surgery, arthroscopy, spine care, and sports trauma rehabilitation.",
      accepted_insurances: ["Star Health", "HDFC ERGO"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 9,
      name: "Dr. Manshi Sen, MD",
      title: "Consultant General Physician",
      specialty: "General Physician",
      city: "Guwahati",
      state: "Assam",
      hospital_name: "Assam Health Institute",
      rating: 4.8,
      reviews_count: 170,
      fee: 700,
      experience: 10,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1594824813566-78a933758f46?w=400&auto=format&fit=crop&q=80",
      bio: "Internal medicine, fever diagnosis, adult wellness screening, and blood pressure tracking.",
      accepted_insurances: ["Care Health", "Star Health"],
      slots: ["11:00 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 4. BIHAR ---
    {
      id: 10,
      name: "Dr. Emily Chen, MD",
      title: "Sports Medicine & Orthopedics",
      specialty: "Orthopedic Doctor",
      city: "Patna",
      state: "Bihar",
      hospital_name: "Patna Specialty Medical Center",
      rating: 4.9,
      reviews_count: 240,
      fee: 1100,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&auto=format&fit=crop&q=80",
      bio: "Sports injury rehab, joint ligament repairs, arthritis management, and spine wellness.",
      accepted_insurances: ["Star Health", "ICICI Lombard"],
      slots: ["10:00 AM", "01:00 PM", "04:00 PM"]
    },
    {
      id: 11,
      name: "Dr. Priya Sharma, MD, DM",
      title: "Senior Neurologist",
      specialty: "Neurologist",
      city: "Patna",
      state: "Bihar",
      hospital_name: "Patna Brain & Neuro Hospital",
      rating: 4.9,
      reviews_count: 280,
      fee: 1300,
      experience: 15,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=400&auto=format&fit=crop&q=80",
      bio: "Stroke management, nerve pain therapies, chronic migraine relief, and epilepsy care.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["09:30 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 12,
      name: "Dr. Aastha Mishra, MS",
      title: "Consultant Eye Specialist",
      specialty: "Ophthalmologist",
      city: "Patna",
      state: "Bihar",
      hospital_name: "Patna Eye Care Center",
      rating: 4.8,
      reviews_count: 185,
      fee: 850,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=400&auto=format&fit=crop&q=80",
      bio: "LASIK laser vision correction, cataract surgery, glaucoma care, and retina evaluation.",
      accepted_insurances: ["Star Health", "Max Bupa"],
      slots: ["11:00 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 5. GOA ---
    {
      id: 13,
      name: "Dr. Michael Reyes, MCh",
      title: "Chief Neurosurgeon",
      specialty: "Neurologist",
      city: "Panaji",
      state: "Goa",
      hospital_name: "Goa Medical College & Hospital",
      rating: 4.9,
      reviews_count: 260,
      fee: 1600,
      experience: 18,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=400&auto=format&fit=crop&q=80",
      bio: "Spine surgery, brain tumor surgery, nerve decompression, and trauma neurosurgery.",
      accepted_insurances: ["Star Health", "Care Health"],
      slots: ["10:00 AM", "02:00 PM", "05:00 PM"]
    },
    {
      id: 14,
      name: "Dr. Huda Khan, MD",
      title: "Senior Endocrinologist",
      specialty: "Endocrinologist",
      city: "Panaji",
      state: "Goa",
      hospital_name: "Panaji Diabetes & Thyroid Care",
      rating: 4.9,
      reviews_count: 210,
      fee: 1100,
      experience: 12,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=400&auto=format&fit=crop&q=80",
      bio: "Diabetes management, thyroid disorders, hormonal imbalance, and metabolic health.",
      accepted_insurances: ["Star Health", "HDFC ERGO"],
      slots: ["09:30 AM", "01:00 PM", "04:30 PM"]
    },
    {
      id: 15,
      name: "Dr. Neha Verma, MD",
      title: "Consultant Pediatrician",
      specialty: "Pediatrician",
      city: "Panaji",
      state: "Goa",
      hospital_name: "Goa Child Health Center",
      rating: 4.8,
      reviews_count: 190,
      fee: 800,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=400&auto=format&fit=crop&q=80",
      bio: "Child healthcare, newborn vaccinations, infant nutrition, and seasonal flu treatments.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["11:00 AM", "02:30 PM", "05:00 PM"]
    },

    // --- 6. HARYANA ---
    {
      id: 16,
      name: "Dr. James O'Connor, MD",
      title: "Pediatric Pulmonologist",
      specialty: "Pediatrician",
      city: "Gurugram",
      state: "Haryana",
      hospital_name: "Gurugram Medanta Hospital",
      rating: 4.9,
      reviews_count: 270,
      fee: 1400,
      experience: 16,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&auto=format&fit=crop&q=80",
      bio: "Pediatric asthma, childhood bronchitis, lung allergies, and respiratory care.",
      accepted_insurances: ["Star Health", "Max Bupa"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 17,
      name: "Dr. Ayesha Khan, MD",
      title: "Senior Dermatologist",
      specialty: "Dermatologist",
      city: "Gurugram",
      state: "Haryana",
      hospital_name: "Fortis Memorial Gurugram",
      rating: 4.9,
      reviews_count: 250,
      fee: 1300,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&auto=format&fit=crop&q=80",
      bio: "Clinical skin specialist, acne therapies, laser procedures, and anti-aging treatments.",
      accepted_insurances: ["HDFC ERGO", "Star Health"],
      slots: ["11:00 AM", "02:00 PM", "05:00 PM"]
    },
    {
      id: 18,
      name: "Dr. Robert Klein, MD",
      title: "Cosmetic Dermatologist",
      specialty: "Dermatologist",
      city: "Gurugram",
      state: "Haryana",
      hospital_name: "Gurugram Aesthetic Center",
      rating: 4.8,
      reviews_count: 220,
      fee: 1500,
      experience: 15,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400&auto=format&fit=crop&q=80",
      bio: "Laser skin resurfacing, chemical peels, hair restoration, and scar removal.",
      accepted_insurances: ["Max Bupa", "Star Health"],
      slots: ["09:30 AM", "01:00 PM", "04:00 PM"]
    },

    // --- 7. HIMACHAL PRADESH ---
    {
      id: 19,
      name: "Dr. Vikram Singh, MD",
      title: "Medical Oncologist",
      specialty: "More Specialties",
      city: "Shimla",
      state: "Himachal Pradesh",
      hospital_name: "Shimla IGMC Medical College",
      rating: 4.9,
      reviews_count: 240,
      fee: 1300,
      experience: 16,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1618498082410-b4aa22193b04?w=400&auto=format&fit=crop&q=80",
      bio: "Chemotherapy management, cancer screening, tumor therapies, and oncology consultation.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 20,
      name: "Dr. Laura Martinez, MD",
      title: "Radiation Oncologist",
      specialty: "More Specialties",
      city: "Shimla",
      state: "Himachal Pradesh",
      hospital_name: "Shimla Specialty Cancer Institute",
      rating: 4.8,
      reviews_count: 210,
      fee: 1400,
      experience: 14,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=400&auto=format&fit=crop&q=80",
      bio: "Radiation therapy planning, targeted tumor radiation, and oncology care.",
      accepted_insurances: ["Star Health", "Care Health"],
      slots: ["09:30 AM", "01:00 PM", "04:00 PM"]
    },
    {
      id: 21,
      name: "Dr. Sunita Rao, MD",
      title: "Internal Medicine Specialist",
      specialty: "General Physician",
      city: "Shimla",
      state: "Himachal Pradesh",
      hospital_name: "Shimla City Medical Center",
      rating: 4.9,
      reviews_count: 180,
      fee: 750,
      experience: 15,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?w=400&auto=format&fit=crop&q=80",
      bio: "Internal medicine, fever diagnosis, altitude sickness, and hypertension management.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["11:00 AM", "02:30 PM", "05:00 PM"]
    },

    // --- 8. JAMMU & KASHMIR ---
    {
      id: 22,
      name: "Dr. David Thompson, MD",
      title: "Family Medicine Specialist",
      specialty: "General Physician",
      city: "Srinagar",
      state: "Jammu & Kashmir",
      hospital_name: "SKIMS Hospital Srinagar",
      rating: 4.8,
      reviews_count: 230,
      fee: 900,
      experience: 14,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80",
      bio: "Comprehensive family healthcare, viral illness treatments, and preventive wellness checks.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:00 PM"]
    },
    {
      id: 23,
      name: "Dr. Kavita Nair, MD",
      title: "Senior Gynecologist",
      specialty: "Gynecologist",
      city: "Srinagar",
      state: "Jammu & Kashmir",
      hospital_name: "Srinagar Maternity Hospital",
      rating: 4.9,
      reviews_count: 260,
      fee: 1000,
      experience: 16,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1594824813566-78a933758f46?w=400&auto=format&fit=crop&q=80",
      bio: "Obstetrics, high-risk pregnancy care, PCOS management, and laparoscopic surgery.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["09:30 AM", "01:00 PM", "04:30 PM"]
    },
    {
      id: 24,
      name: "Dr. Amanda Foster, MD",
      title: "Obstetrics & Gynecology Specialist",
      specialty: "Gynecologist",
      city: "Srinagar",
      state: "Jammu & Kashmir",
      hospital_name: "Srinagar Women Care Institute",
      rating: 4.8,
      reviews_count: 210,
      fee: 1100,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80",
      bio: "Maternal care, painless delivery guidance, prenatal wellness, and reproductive health.",
      accepted_insurances: ["Star Health", "Max Bupa"],
      slots: ["11:00 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 9. JHARKHAND ---
    {
      id: 25,
      name: "Dr. Arjun Mehta, MD",
      title: "Senior Consultant Psychiatrist",
      specialty: "Psychiatrist",
      city: "Ranchi",
      state: "Jharkhand",
      hospital_name: "CIP Ranchi Mental Health Center",
      rating: 4.9,
      reviews_count: 280,
      fee: 1200,
      experience: 15,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=400&auto=format&fit=crop&q=80",
      bio: "Stress management, depression counselling, anxiety therapies, and mood disorder treatment.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 26,
      name: "Dr. Rachel Green, MD",
      title: "Child & Adolescent Psychiatrist",
      specialty: "Psychiatrist",
      city: "Ranchi",
      state: "Jharkhand",
      hospital_name: "Ranchi Mind & Wellness Institute",
      rating: 4.9,
      reviews_count: 230,
      fee: 1300,
      experience: 14,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80",
      bio: "ADHD therapy, adolescent behavioral guidance, school stress counselling, and emotional wellness.",
      accepted_insurances: ["Care Health", "Star Health"],
      slots: ["11:00 AM", "02:30 PM", "05:00 PM"]
    },

    // --- 10. KERALA ---
    {
      id: 27,
      name: "Dr. Gurleen Kaur, MD",
      title: "Senior Cardiologist",
      specialty: "Cardiologist",
      city: "Kochi",
      state: "Kerala",
      hospital_name: "Kochi Aster Medcity",
      rating: 4.9,
      reviews_count: 290,
      fee: 1400,
      experience: 16,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&auto=format&fit=crop&q=80",
      bio: "Angioplasty, heart valve disorders, cardiac rehabilitation, and preventive cardiology.",
      accepted_insurances: ["Star Health", "ICICI Lombard"],
      slots: ["09:30 AM", "01:00 PM", "04:00 PM"]
    },
    {
      id: 28,
      name: "Dr. Anil Kapoor, MS",
      title: "Senior Orthopedic Surgeon",
      specialty: "Orthopedic Doctor",
      city: "Kochi",
      state: "Kerala",
      hospital_name: "Kochi VPS Lakeshore",
      rating: 4.9,
      reviews_count: 310,
      fee: 1300,
      experience: 18,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80",
      bio: "Joint replacement, spine surgery, fracture trauma care, and arthroscopy.",
      accepted_insurances: ["Star Health", "HDFC ERGO"],
      slots: ["10:30 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 11. MANIPUR ---
    {
      id: 29,
      name: "Dr. Shivani Sharma, MD",
      title: "Consultant Dermatologist",
      specialty: "Dermatologist",
      city: "Imphal",
      state: "Manipur",
      hospital_name: "Imphal RIMS Hospital",
      rating: 4.8,
      reviews_count: 170,
      fee: 750,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&auto=format&fit=crop&q=80",
      bio: "Clinical skin specialist, eczema, acne treatments, and hair fall therapies.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:00 PM"]
    },
    {
      id: 30,
      name: "Dr. Rajesh Malhotra, MD",
      title: "Senior Cardiologist",
      specialty: "Cardiologist",
      city: "Imphal",
      state: "Manipur",
      hospital_name: "Imphal Heart & Medical Center",
      rating: 4.9,
      reviews_count: 220,
      fee: 1300,
      experience: 17,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80",
      bio: "Heart attack prevention, BP control, echocardiogram analysis, and lipid management.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["09:00 AM", "12:30 PM", "03:30 PM"]
    },

    // --- 12. MEGHALAYA ---
    {
      id: 31,
      name: "Dr. Simran Kaur, MD",
      title: "Consultant Gynecologist",
      specialty: "Gynecologist",
      city: "Shillong",
      state: "Meghalaya",
      hospital_name: "Shillong NEIGRIHMS Hospital",
      rating: 4.9,
      reviews_count: 190,
      fee: 900,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80",
      bio: "Maternal care, prenatal wellness, PCOS therapies, and high-risk pregnancy guidance.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "02:00 PM", "05:00 PM"]
    },
    {
      id: 32,
      name: "Dr. Priya Sharma, MD, DM",
      title: "Senior Neurologist",
      specialty: "Neurologist",
      city: "Shillong",
      state: "Meghalaya",
      hospital_name: "Shillong Neuro Institute",
      rating: 4.8,
      reviews_count: 210,
      fee: 1200,
      experience: 15,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=400&auto=format&fit=crop&q=80",
      bio: "Stroke rehabilitation, nerve pain therapies, chronic headache relief, and memory care.",
      accepted_insurances: ["Star Health", "Care Health"],
      slots: ["09:30 AM", "01:00 PM", "04:30 PM"]
    },

    // --- 13. MIZORAM ---
    {
      id: 33,
      name: "Dr. Sakshi Gupta, MD",
      title: "Lead Pediatrician",
      specialty: "Pediatrician",
      city: "Aizawl",
      state: "Mizoram",
      hospital_name: "Aizawl Civil Hospital",
      rating: 4.8,
      reviews_count: 160,
      fee: 700,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=400&auto=format&fit=crop&q=80",
      bio: "Newborn vaccinations, infant nutrition, childhood allergy care, and pediatric medicine.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:00 PM"]
    },
    {
      id: 34,
      name: "Dr. Siddarth Verma, MS",
      title: "Senior Orthopedic Surgeon",
      specialty: "Orthopedic Doctor",
      city: "Aizawl",
      state: "Mizoram",
      hospital_name: "Aizawl Ortho Clinic",
      rating: 4.9,
      reviews_count: 150,
      fee: 850,
      experience: 13,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80",
      bio: "Fracture management, joint pain relief, knee trauma care, and spine wellness.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["11:00 AM", "02:30 PM", "05:00 PM"]
    },

    // --- 14. NAGALAND ---
    {
      id: 35,
      name: "Dr. Manshi Sen, MD",
      title: "Consultant General Physician",
      specialty: "General Physician",
      city: "Kohima",
      state: "Nagaland",
      hospital_name: "Kohima Naga Hospital",
      rating: 4.8,
      reviews_count: 140,
      fee: 650,
      experience: 10,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1594824813566-78a933758f46?w=400&auto=format&fit=crop&q=80",
      bio: "Fever diagnosis, adult wellness screening, BP control, and preventive healthcare.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["09:30 AM", "01:00 PM", "04:00 PM"]
    },
    {
      id: 36,
      name: "Dr. Aastha Mishra, MS",
      title: "Consultant Eye Specialist",
      specialty: "Ophthalmologist",
      city: "Kohima",
      state: "Nagaland",
      hospital_name: "Kohima Eye Institute",
      rating: 4.9,
      reviews_count: 135,
      fee: 750,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=400&auto=format&fit=crop&q=80",
      bio: "Cataract evaluation, vision correction, dry eye syndrome care, and eye checkups.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["10:30 AM", "02:00 PM", "04:30 PM"]
    },

    // --- 15. ODISHA ---
    {
      id: 37,
      name: "Dr. Neha Verma, MD",
      title: "Senior Pediatrician",
      specialty: "Pediatrician",
      city: "Bhubaneswar",
      state: "Odisha",
      hospital_name: "Bhubaneswar AIIMS Hospital",
      rating: 4.9,
      reviews_count: 250,
      fee: 900,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&auto=format&fit=crop&q=80",
      bio: "Infant growth monitoring, vaccination schedules, pediatric infections, and nutrition guidance.",
      accepted_insurances: ["Star Health", "Ayushman Bharat"],
      slots: ["09:00 AM", "12:30 PM", "03:30 PM"]
    },
    {
      id: 38,
      name: "Dr. Vikram Singh, MD",
      title: "Medical Oncologist",
      specialty: "More Specialties",
      city: "Bhubaneswar",
      state: "Odisha",
      hospital_name: "Bhubaneswar KIMS Hospital",
      rating: 4.9,
      reviews_count: 280,
      fee: 1500,
      experience: 17,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1618498082410-b4aa22193b04?w=400&auto=format&fit=crop&q=80",
      bio: "Chemotherapy management, tumor immunotherapy, precision oncology, and cancer screening.",
      accepted_insurances: ["Star Health", "Care Health"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },

    // --- 16. SIKKIM ---
    {
      id: 39,
      name: "Dr. Huda Khan, MD",
      title: "Lead General Physician",
      specialty: "General Physician",
      city: "Gangtok",
      state: "Sikkim",
      hospital_name: "Gangtok STNM Hospital",
      rating: 4.9,
      reviews_count: 160,
      fee: 700,
      experience: 12,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=400&auto=format&fit=crop&q=80",
      bio: "Internal medicine, altitude sickness care, diabetes tracking, and routine wellness checkups.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:00 PM"]
    },
    {
      id: 40,
      name: "Dr. Ayesha Khan, MD",
      title: "Consultant Dermatologist",
      specialty: "Dermatologist",
      city: "Gangtok",
      state: "Sikkim",
      hospital_name: "Gangtok Skin Clinic",
      rating: 4.8,
      reviews_count: 140,
      fee: 800,
      experience: 11,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&auto=format&fit=crop&q=80",
      bio: "Acne treatments, chemical peels, hair fall care, and skin allergy therapies.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["11:00 AM", "02:00 PM", "05:00 PM"]
    },

    // --- 17. TRIPURA ---
    {
      id: 41,
      name: "Dr. Arjun Mehta, MD",
      title: "Senior Psychiatrist",
      specialty: "Psychiatrist",
      city: "Agartala",
      state: "Tripura",
      hospital_name: "Agartala AGMC Hospital",
      rating: 4.9,
      reviews_count: 190,
      fee: 1000,
      experience: 15,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=400&auto=format&fit=crop&q=80",
      bio: "Mental wellness care, depression counselling, anxiety management, and stress reduction.",
      accepted_insurances: ["Ayushman Bharat", "Star Health"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 42,
      name: "Dr. Kavita Nair, MD",
      title: "Consultant Gynecologist",
      specialty: "Gynecologist",
      city: "Agartala",
      state: "Tripura",
      hospital_name: "Agartala Women Care Hospital",
      rating: 4.8,
      reviews_count: 165,
      fee: 850,
      experience: 13,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80",
      bio: "Maternity care, high-risk pregnancy management, PCOS treatment, and prenatal wellness.",
      accepted_insurances: ["Ayushman Bharat", "Care Health"],
      slots: ["09:30 AM", "01:00 PM", "04:00 PM"]
    },

    // --- 18. UTTARAKHAND ---
    {
      id: 43,
      name: "Dr. Rajesh Malhotra, MD",
      title: "Senior Cardiologist",
      specialty: "Cardiologist",
      city: "Dehradun",
      state: "Uttarakhand",
      hospital_name: "Dehradun Max Hospital",
      rating: 4.9,
      reviews_count: 280,
      fee: 1500,
      experience: 18,
      gender: "Male",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80",
      bio: "Angioplasty, heart failure care, coronary artery disease management, and pacemaker installation.",
      accepted_insurances: ["Star Health", "HDFC ERGO"],
      slots: ["10:00 AM", "01:30 PM", "04:30 PM"]
    },
    {
      id: 44,
      name: "Dr. Shivani Sharma, MD",
      title: "Consultant Dermatologist",
      specialty: "Dermatologist",
      city: "Dehradun",
      state: "Uttarakhand",
      hospital_name: "Dehradun Skin & Laser Clinic",
      rating: 4.9,
      reviews_count: 220,
      fee: 1100,
      experience: 12,
      gender: "Female",
      telehealth: true,
      photo: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&auto=format&fit=crop&q=80",
      bio: "Laser skin procedures, acne therapies, hair fall restoration, and eczema treatment.",
      accepted_insurances: ["Star Health", "Max Bupa"],
      slots: ["11:00 AM", "02:30 PM", "05:00 PM"]
    }
  ],

  specialties: [
    "General Physician",
    "Cardiologist",
    "Dermatologist",
    "Orthopedic Doctor",
    "Pediatrician",
    "Gynecologist",
    "Dentist",
    "Ophthalmologist",
    "ENT Specialist",
    "Neurologist",
    "Gastroenterologist",
    "Pulmonologist",
    "Nephrologist",
    "Endocrinologist",
    "Psychiatrist",
    "More Specialties"
  ],

  cities: [
    "All",
    "Andhra Pradesh (Visakhapatnam)",
    "Arunachal Pradesh (Itanagar)",
    "Assam (Guwahati)",
    "Bihar (Patna)",
    "Chhattisgarh (Raipur)",
    "Delhi NCR (New Delhi)",
    "Goa (Panaji)",
    "Gujarat (Ahmedabad / Surat)",
    "Haryana (Gurugram)",
    "Himachal Pradesh (Shimla)",
    "Jammu & Kashmir (Srinagar)",
    "Jharkhand (Ranchi)",
    "Karnataka (Bengaluru)",
    "Kerala (Kochi / Trivandrum)",
    "Madhya Pradesh (Bhopal / Indore)",
    "Maharashtra (Mumbai / Pune / Nagpur)",
    "Manipur (Imphal)",
    "Meghalaya (Shillong)",
    "Mizoram (Aizawl)",
    "Nagaland (Kohima)",
    "Odisha (Bhubaneswar)",
    "Punjab & Chandigarh (Amritsar / Mohali)",
    "Rajasthan (Jaipur)",
    "Sikkim (Gangtok)",
    "Tamil Nadu (Chennai)",
    "Telangana (Hyderabad)",
    "Tripura (Agartala)",
    "Uttar Pradesh (Lucknow / Noida)",
    "Uttarakhand (Dehradun)",
    "West Bengal (Kolkata)"
  ],

  insurances: [
    "All",
    "Star Health",
    "HDFC ERGO",
    "ICICI Lombard",
    "Max Bupa",
    "Care Health",
    "Ayushman Bharat",
    "Blue Cross Blue Shield",
    "Aetna"
  ]
};
window.CARE_DATA = CARE_DATA;
